package org.bouncycastle.asn1.u2;

import org.bouncycastle.asn1.m;

public abstract interface p
{
  public static final m A2;
  public static final m A3;
  public static final m B2;
  public static final m B3;
  public static final m C2;
  public static final m C3;
  public static final m D2;
  public static final m D3;
  public static final m E2;
  public static final m E3;
  public static final m F2;
  public static final m F3;
  public static final m G2;
  public static final m G3;
  public static final m H2;
  public static final m I2;
  public static final m J2;
  public static final m K2;
  public static final m L2;
  public static final m M2;
  public static final m N2;
  public static final m O2;
  public static final m P2;
  public static final m Q2;
  public static final m R2;
  public static final m S2;
  public static final m T2;
  public static final m U2;
  public static final m V2;
  public static final m W2;
  public static final m X2;
  public static final m Y2;
  public static final m Z2;
  public static final m a3;
  public static final m b3;
  public static final m c3;
  public static final m d3;
  public static final m e3;
  public static final m f3;
  public static final m g3;
  public static final m h3;
  public static final m i3;
  public static final m j3;
  public static final m k3;
  public static final m l3;
  public static final m m3;
  public static final m n3;
  public static final m o3;
  public static final m q3;
  public static final m r2;
  public static final m r3;
  public static final m s2;
  public static final m s3;
  public static final m t2;
  public static final m t3;
  public static final m u2;
  public static final m u3;
  public static final m v2;
  public static final m v3;
  public static final m w2;
  public static final m w3;
  public static final m x2;
  public static final m x3;
  public static final m y2;
  public static final m y3;
  public static final m z2;
  public static final m z3;
  
  static
  {
    m localm1 = new m("1.2.840.10045");
    r2 = localm1;
    m localm2 = localm1.m("1");
    s2 = localm2;
    t2 = localm2.m("1");
    localm2 = localm2.m("2");
    u2 = localm2;
    v2 = localm2.m("3.1");
    w2 = localm2.m("3.2");
    x2 = localm2.m("3.3");
    m localm3 = localm1.m("4");
    y2 = localm3;
    z2 = localm3.m("1");
    localm2 = localm1.m("2");
    A2 = localm2;
    B2 = localm2.m("1");
    localm2 = localm3.m("3");
    C2 = localm2;
    D2 = localm2.m("1");
    E2 = localm2.m("2");
    F2 = localm2.m("3");
    G2 = localm2.m("4");
    localm2 = localm1.m("3");
    H2 = localm2;
    localm1 = localm2.m("0");
    I2 = localm1;
    J2 = localm1.m("1");
    K2 = localm1.m("2");
    L2 = localm1.m("3");
    M2 = localm1.m("4");
    N2 = localm1.m("5");
    O2 = localm1.m("6");
    P2 = localm1.m("7");
    Q2 = localm1.m("8");
    R2 = localm1.m("9");
    S2 = localm1.m("10");
    T2 = localm1.m("11");
    U2 = localm1.m("12");
    V2 = localm1.m("13");
    W2 = localm1.m("14");
    X2 = localm1.m("15");
    Y2 = localm1.m("16");
    Z2 = localm1.m("17");
    a3 = localm1.m("18");
    b3 = localm1.m("19");
    c3 = localm1.m("20");
    localm1 = localm2.m("1");
    d3 = localm1;
    e3 = localm1.m("1");
    f3 = localm1.m("2");
    g3 = localm1.m("3");
    h3 = localm1.m("4");
    i3 = localm1.m("5");
    j3 = localm1.m("6");
    k3 = localm1.m("7");
    l3 = new m("1.2.840.10040.4.1");
    m3 = new m("1.2.840.10040.4.3");
    localm1 = new m("1.3.133.16.840.63.0");
    n3 = localm1;
    o3 = localm1.m("2");
    q3 = localm1.m("3");
    r3 = localm1.m("16");
    localm1 = new m("1.2.840.10046");
    s3 = localm1;
    t3 = localm1.m("2.1");
    localm1 = localm1.m("3");
    u3 = localm1;
    v3 = localm1.m("1");
    w3 = localm1.m("2");
    x3 = localm1.m("3");
    y3 = localm1.m("4");
    z3 = localm1.m("5");
    A3 = localm1.m("6");
    B3 = localm1.m("7");
    C3 = localm1.m("8");
    localm1 = new m("1.3.133.16.840.9.44");
    D3 = localm1;
    localm1 = localm1.m("1");
    E3 = localm1;
    F3 = localm1.m("1");
    G3 = localm1.m("2");
  }
}


/* Location:              C:\Users\User\Desktop\decompile\jdgui110\Tapojar.jar!\org\bouncycastle\asn1\u2\p.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */